version: "3.9"

services:
  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: boletos_db
      POSTGRES_USER: valerio
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"

  web:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_NAME=boletos_db
      - DB_USER=valerio
      - DB_PASSWORD=123456
      - DB_HOST=db
      - DB_PORT=5432

volumes:
  postgres_data:
